### ISSUE TITLE
Cant start on arch

### ISSUE THREAD

**Issue by GhishNchips** [knapsu/plex-media-player-appimage#18]
I cant start this appimage on arch linux. According to the log this is the problem
2018-09-12 14:11:18 [ FATAL ] Log.cpp @ 41 - "Could not initialize GLX" 
Thanks in advance for help.

**Comment by supagu** [comment]
Same here.

Also trying the version with the older UI also doesnt run.
/tmp/.mount_Plex_Me2Pvft/usr/bin/plexmediaplayer: symbol lookup error: /usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var

**Comment by probonopd** [comment]
Rebuilding the AppImages (using the latest AppImage generation tools) should fix the issue. libfreetype (FT_*) has been added to our blacklist.

Reference:
https://github.com/probonopd/linuxdeployqt/issues/259

**Comment by knapsu** [comment]
Hi @hallonfras and @supagu. Sorry for late response. Been busy with other projects.

Can you check if  version [2.20.0.909-46413dd1](https://knapsu.eu/data/plex/Plex_Media_Player_2.20.0.909-46413dd1_x64.AppImage) works for you? It does not contain the mentioned `libfreetype.so`.

**Comment by supagu** [comment]
Yes that version is working now!

The old version still doesnt work:

[s@s-pc Applications]$ ./Plex_Media_Player_1.3.12.755-fed6185a_x64.AppImage 

(process:19399): GLib-CRITICAL **: 09:03:06.986: g_file_test: assertion 'filename != NULL' failed
/tmp/.mount_Plex_MMr7DBV/usr/bin/plexmediaplayer: symbol lookup error: /usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var

**Comment by knapsu** [comment]
@supagu I am unable to build **v1.3.12** as the proprietary packages needed for it are not available any more for download. Plex Inc has turned off the Conan packages repository that was used for building older PMP versions. New  versions use a different package management system so they are not affected. Closing the issue as it is resolved as best as I could.

**Comment by galfwender** [comment]
I have the same issue "Could not initialize GLX" with 2.26.0.947 and 2.25.0.940 on Antergos.  2.24.0.924 works.
